baseurl = "/"
languageCode = "en-us"
title = "Featherₜₛ"
theme = "feather-ts"
metadataformat = "yaml"
canonifyurls = true
relativeURLS = true

ignoreFiles = ["^/app/"]

# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-84969611-1"

[params]
	# General information
	author = "Andreas Prudzilko"
	description = "Feather TS - official Website"
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/mendrik/feather"

	version = "ᵃˡᵖʰᵃ"
	logo = "images/logo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["css/tweaks.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

[social]
	twitter = ""
	github  = "mendrik"
	email   = "mendrik76@gmail.com"

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 10

[[menu.main]]
	name   = "Installation"
	url    = "installation/"
	weight = 20

[[menu.main]]
	name   = "Docs"
	url    = "documentation/"
	weight = 30

[[menu.main]]
	name   = "Questions"
	url    = "faq/"
	weight = 40

[[menu.main]]
	name   = "Issues"
	url    = "https://github.com/mendrik/feather/issues"
	weight = 50

